loader:
    url: 'http://www.google.com/jsapi?key=%s'

    'hashmarkd.com':
        api_key: 'ABQIAAAAuMuGdVBRzQKrZLeH5DX9hRTr60sv5ke-QG0oauwJk7-qwQ4SLRSqslGQSwaQacO1MOQg-Ewb8SRkog'

    'hashmarkd.local':
        api_key: 'ABQIAAAAuMuGdVBRzQKrZLeH5DX9hRQsatN46t95su4YX1Ry0Tm_rRBbGxSwW5ylOrXq1mFqF95uPyg0upwRFQ'

    'hashmarkd.appspot.com':
        api_key: 'ABQIAAAAuMuGdVBRzQKrZLeH5DX9hRQsAg9v4L4SQDEavpVmVdf_T9EJchROkwm2IQxrR4EdJbTJVfzHfQMwNg'

